### ISSUE TITLE
User request: make sources in Log->Source persistent

### ISSUE THREAD

**Issue by janwilmans** [CobaltFusion/DebugViewPP#213]
Requested by the DAQ team: make the log sources added through Log->Source persistent,
they use UDP sources a lot and are annoyed that they have to be added every time debugview is started.

**Comment by janwilmans** [comment]
![image](https://cloud.githubusercontent.com/assets/5933444/13900498/22bc756e-ee08-11e5-813b-8641b3446aca.png)

**Comment by harriv** [comment]
I'd like to see this fixed (and published), this is biggest issue preveting "easy usage" of the DebugView++ for me.

**Comment by janwilmans** [comment]
thanks for your feedback, I will do what I can to prioritize this issue.


On 30 May 2016 at 11:10, harriv <notifications@github.com> wrote:

> I'd like to see this fixed (and published), this is biggest issue
> preveting "easy usage" of the DebugView++ for me.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/djeedjay/DebugViewPP/issues/213#issuecomment-222448601>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFqJhDmZyvGdHc4PNT63VcVEX2e5kyaSks5qGqlrgaJpZM4GkokQ>
> .
>



-- 
Met vriendelijke groeten,

Jan Wilmans

**Comment by harriv** [comment]
History size could be also permanent setting.

**Comment by harriv** [comment]
Sources could be saved as a part of configuration? (File -> Save Configuration.)

**Comment by janwilmans** [comment]
Thanks again for reporting, maybe you can fix it? I'm happy to accept pull-requests and as I'm currently working on a different feature and the input plugin-structure is under discussion, It' not very keep on fixing this yet.

**Comment by harriv** [comment]
I'm not Visual Studio user.. Maybe I need find out how it works someday :)

**Comment by udoe** [comment]
I would like to see the same feature: Make UDP (and TCP) sources setup persistent in the dbconf file. What is the status of this issue? I could try to find some time to work on it...

**Comment by janwilmans** [comment]
Very nice, I'll look at this!

**Comment by janwilmans** [comment]
forgot to close the issue, @udoe 's patch implemented this.
