### ISSUE TITLE
Would like to be able to filter by PID

### ISSUE THREAD

**Issue by GregB-Roberts** [CobaltFusion/DebugViewPP#299]
Hi

In my context there are 5 processes of the same name, and I would like to filter by the process PID 

The work around is to save the log and grep for the pid and resave the output, but obviously this cant be done in real time.

Thanks

**Comment by janwilmans** [comment]
thanks for your suggestion!
how would you feel about being able to rename a process ?

**Comment by janwilmans** [comment]
alternatively, we could add an option to prefix the processID to the message like dbgview does 
````
[PID] message
ie:
[4440] Message without newline  (tid: 9001)
[4440] Message without newline  (tid: 9001)
```
then it could be filtered by message content again

**Comment by janwilmans** [comment]
as #99 and #114 suggested, renaming the process is better because that way it is easier to interpret the data after saving+loading it later.

**Comment by DannyBunny** [comment]
Adding an option to output the [PID] as the message prefix is a good solution.
I personally don't have the need to rename a process, but I guess that would help in filtering on the specific process as well, as long as the renaming is done per PID.
