### ISSUE TITLE
Menu item for copying only "Message" column

### ISSUE THREAD

**Issue by arkinform** [CobaltFusion/DebugViewPP#302]
In our project we use DebugOutput for logging SQL quiries with parameter values. And we often need to copy some querу and execute it in other program. But DebugViewPP always copy with all column values. Will be very usefull to make separate context menu item for copy selected text only from "Message" column.

**Comment by janwilmans** [comment]
You can already select a piece of the message to copy it, are you aware of that? and still think its useful of have a separate 'copy messsage' item ?

**Comment by arkinform** [comment]
1. I can not select "piece of the message" in multiple rows 
2. Selecting long text with mouse is not very convenient

**Comment by janwilmans** [comment]
I see, I'll create something soon!

**Comment by arkinform** [comment]
> I see, I'll create something soon!

Do you plan to make something like "Copy message" in near future?

**Comment by janwilmans** [comment]
I totally forgot about this one, sorry about that, I'm in the middle of a small unicode refactoring right now, but I will see what I can do.

**Comment by janwilmans** [comment]
I've added a context-menu item, please try it: 
https://github.com/CobaltFusion/DebugViewPP/releases/tag/v1.8.0.25

**Comment by janwilmans** [comment]
implemented in 4250e58609172f0a49d5a46d42ef31cdbc7e883b

**Comment by arkinform** [comment]
"Copy messages" item works fine, thank you.

A few remarks:
1. I think that it will be better to preserve old "Copy" item before "Copy messages" item in menu for backward compatibility.
2. Please, add shortcut for "Copy messages", for example, Shift + Ctrl + C
3. Selection with Shift + Up/Down does not work

**Comment by janwilmans** [comment]
rework.

**Comment by janwilmans** [comment]
Selection with Shift + Up/Down should be fixed in
https://github.com/CobaltFusion/DebugViewPP/releases/tag/v1.8.0.27

**Comment by arkinform** [comment]
1. I have checked selection with Shift + Up/Down, works fine
2. When I click right mouse button on "Process" column then I see old "Copy" item and it does not work

**Comment by janwilmans** [comment]
What do you mean with 'does not work' ? 
you expected it to copy the process name? 
I tried it and it copies the whole line (like the old copy) here...

**Comment by arkinform** [comment]
> I tried it and it copies the whole line (like the old copy) here...

In my case keyboard shortcut Ctrl+C works fine but mouse click on menu item "Copy" (visible only for "Process" column) does not copy anything.

And I think that it is oddly to see "Copy" menu item only for "Process" column.

**Comment by arkinform** [comment]
![image](https://user-images.githubusercontent.com/32133372/44591484-81edab00-a7c6-11e8-9fd0-142147c0d430.png)

**Comment by janwilmans** [comment]
The fact that copy on one context menu works, but not on the other is very strange, the logic behind the two menu items is identical:

![image](https://user-images.githubusercontent.com/5933444/44608520-48cc2f80-a7f4-11e8-9d1a-5936a523a362.png)

**Comment by arkinform** [comment]
Sorry for delay. I have tried last build v1.8.0.34, in this build everything works fine.
Shortcut Shift + Ctrl + C works fine too but I don't see shortcut hint for item "Copy Messages" in context menu.

**Comment by janwilmans** [comment]
I've added the shortcut hint, it well be in the next release. Thanks for testing, it is much appreciated!
