### ISSUE TITLE
Need an easy way to exclude empty lines emitted by OutputDebugString

### ISSUE THREAD

**Issue by mydeveloperday** [CobaltFusion/DebugViewPP#313]
Some 3rd party dll which my application loads calls OutputDebugString with what appears to be empty lines

It would be good if there was an easy way to exclude empty lines

![image](https://user-images.githubusercontent.com/16046346/33771672-c56cc172-dc29-11e7-9163-5416cac4439b.png)

**Comment by mydeveloperday** [comment]
I can see it should do, but it didn't, but actually using \S and include seemed to pull in everything that wasn't just whitespace

![image](https://user-images.githubusercontent.com/16046346/33835421-555325b4-de7e-11e7-8b1f-795c3f143587.png)

**Comment by janwilmans** [comment]
i'll look into it

**Comment by janwilmans** [comment]
This works
![image](https://user-images.githubusercontent.com/5933444/33846192-23dcf6ea-dea6-11e7-8f70-c4dc9d4251b2.png)

Still looking into why \s*  or $\s* does not work

**Comment by janwilmans** [comment]
It actually makes sense,  regex: \s* is saying; contains zero or more whitespace characters , well any string matches that, "foo" also contains 'zero whitespace characters' . I do wish there was a nicer way to filter empty lines.
