### ISSUE TITLE
Load configuration fails

### ISSUE THREAD

**Issue by mmusterd** [CobaltFusion/DebugViewPP#322]
Exception 'conversion of data to type "bool" failed' occured at d:\project\debugviewpp\debugview++\mainframe.cpp:260

Attached is the "faulty" configuration, as created by debugview++ 1.8.0.13. The extension is renamed from dbconf to txt so github allows attaching the file.

[no_disabled_filters.txt](https://github.com/CobaltFusion/DebugViewPP/files/2053981/no_disabled_filters.txt)

**Comment by janwilmans** [comment]
fixed in d5ea37aa15c5939bc69db15fc646f89dfc8e60f2
