### ISSUE TITLE
Page up goes only one line up in filtered view

### ISSUE THREAD

**Issue by harriv** [CobaltFusion/DebugViewPP#324]
If I've filtered view (pretty sparse filter) and cursor is at the first line of the visible data, page up goes only one line up (similar to arrow up).

**Comment by janwilmans** [comment]
I've tried to reprocude can't I can not get it to happen, a source code review did also not turn up a problem. Get you provide the filter set? (export the set?)

**Comment by janwilmans** [comment]
close due to no response
