### ISSUE TITLE
case sensitive  filter

### ISSUE THREAD

**Issue by vlovo** [CobaltFusion/DebugViewPP#331]
Congrats ! 
for me it is a long seeking  drop in replacement for (Bare)Tail.  DebugView++ even better combines  this tailing feature with the power  of  Notepad++ etc.  
Thank you very much for this neat piece of software. 

A few remarks:

- in case of drag and drop a file  to debugview++   sometimes the tail feature did not start to work immedately.. I  am not sure what the conditions are . I will investigate a little bit further. Do you have any recommendations ? 

- for me it is more feasible  to  be  case sensitve  regarding the filters.   Maybe an opt-in would be nice...

**Comment by vlovo** [comment]
case sensitive search: 
Ok, I see ... maybe one can come up with a minimal invasive modification like extending the match type 
likewise 
static const MatchType::type MessageMatchTypes[] = {MatchType::Simple, MatchType::Wildcard, MatchType::Regex, MatchType::RegexGroups,_**MatchType::RegexCase**_};
and also
#define MATCH_TYPES() \
	MATCH_TYPE(Simple, 0) \
	MATCH_TYPE(Wildcard, 1) \
	MATCH_TYPE(Regex, 2) \
	MATCH_TYPE(RegexGroups, 3)\
	_**MATCH_TYPE(RegexCase, 4)**_

**Comment by janwilmans** [comment]
![image](https://user-images.githubusercontent.com/5933444/44632882-3d067780-a972-11e8-8e2d-53c763bec1f4.png)

highlighting capital 'O' in green, while lower-case 'o' is red

**Comment by janwilmans** [comment]
implemented in aca8877197c88c7410c9d6f160a5ca1f6517aa40

**Comment by janwilmans** [comment]
please try out https://github.com/CobaltFusion/DebugViewPP/releases/tag/v1.8.0.34

**Comment by vlovo** [comment]
Great ! Works lile a charm.

**Comment by janwilmans** [comment]
good to hear, glad I could help
