### ISSUE TITLE
Debugview++ classified as Trojan Win32/Zpevdo.B by Windows Defender

### ISSUE THREAD

**Issue by monty241** [CobaltFusion/DebugViewPP#353]
Reproduction:
* Download debugview++.msi version 1.8.0.44 using Google Chrome (productie channel).
* Automatically blocked and classified as trojan Win32/Zpevdo.B

See pictures.

![image](https://user-images.githubusercontent.com/7579444/55307269-57985600-5457-11e9-95b3-c9829f38dbac.png)

![image](https://user-images.githubusercontent.com/7579444/55307275-5a934680-5457-11e9-84cf-6d8badfe57d5.png)

![image](https://user-images.githubusercontent.com/7579444/55307279-5e26cd80-5457-11e9-9453-8c3119cf0031.png)

**Comment by janwilmans** [comment]
I have had similar problems myself at my company, where mcafee classified it as a different kind of heuristic thread. I've tried to remove certain API calls to see if that would have, but no luck... I would be happy to fix this but, I have no idea why its being classified as a trojan. Of course debugview++ does use debug-api's but, there is really no choise, its a debugging application :)

**Comment by janwilmans** [comment]
If you google Zpevdo.B you will see that more people struggle with false positives of this kind...

**Comment by janwilmans** [comment]
I've submitted this case to Windows Defender
![image](https://user-images.githubusercontent.com/5933444/55308658-ac3dd000-545b-11e9-9195-263cdace0255.png)

**Comment by janwilmans** [comment]
Good news, 
![image](https://user-images.githubusercontent.com/5933444/55317215-5b84a200-5470-11e9-9b18-dabbe8efc745.png)

**Comment by janwilmans** [comment]
closing... please re-open if more troubles are encountered
