### ISSUE TITLE
v1.8.0.46 - 32 bit version marked as infected

### ISSUE THREAD

**Issue by LVLVbNH** [CobaltFusion/DebugViewPP#358]
v1.8.0.46 - 32 bit release marked as infected file. 
Proof: https://www.virustotal.com/gui/file/9c7129b25b239c055ee4a8e53dfe4db16e37ca692b1b36ca9443fa086cf93ce1/detection
Even if it false warning Microsoft Defender (determines Trojan:Win32/Tiggre!plock) do not let you use or even download exe or zip file.

**Comment by janwilmans** [comment]
I've unfortunately had more reports of this, using the x64 version works around this. I'm trying to get this fixed but its not working so far
