### ISSUE TITLE
Alert user when running another instance of DebugViewPP

### ISSUE THREAD

**Issue by tmplinshi** [CobaltFusion/DebugViewPP#360]
Hi,

This happened to me many times that I forgot I already opened DebugViewPP, and I'm staring at the screen wondering why there is no output in DebugViewPP..

I don't know what the purpose of a paused DebugViewPP, but maybe popup a MsgBox or something? The status bar's text "Paused" is not easy to noticed.

**Comment by janwilmans** [comment]
I see how this can get confusing, but I'm not sure what you're proposing. Popup a message when?

**Comment by tmplinshi** [comment]
> when starting a second debugview instance when there is already one running
This was what I meant. Thanks.

**Comment by janwilmans** [comment]
Agreed, I will add this warning message at startup. In fact I think it used to be there, and I'm not sure when it was removed :)

**Comment by janwilmans** [comment]
solved, a message pops up now if you start debugview++ twice
