### ISSUE TITLE
VSIX not compatible with Visual Studio 2019

### ISSUE THREAD

**Issue by lheinold** [CobaltFusion/DebugViewPP#364]
I am trying to install the vsix in visual studio 2019. Unfortunately I get the following error message: 

The following extensions are not compatible with Visual Studio.
Installation may cause Visual Studio to be unstable.
    - CobaltFusion Output Window Forwarding
[OK]

It doesn't allow me to install anyway, and clicking [OK] just closes the installer.

Is there a workaround? Is there any way we can get a vsix compatible with 2019? (I read the last issue about backwards compatibility, maybe we can get a second vsix?)

**Comment by janwilmans** [comment]
vs2019 broken compatibility with older extensions, a new vs2022 extension is now available at https://marketplace.visualstudio.com/items?itemName=JanWilmans.OutputForwarder2022
