### ISSUE TITLE
Feature Request: Filter by PID

### ISSUE THREAD

**Issue by MarkGoldberg** [CobaltFusion/DebugViewPP#367]
Option to filter not just by process name, but by PID 
useful when there are multiple instances of the same process name running

**Comment by MarkGoldberg** [comment]
Ah,  "Options > Prefix PID" can be used to add the PID to the message text, and we can filter from there.
<miss-Litella> never mind </miss-Litella>

**Comment by janwilmans** [comment]
yes, the actual filtering had all kinds of lifetime complications,  so that
was easiest...
