### ISSUE TITLE
New useability

### ISSUE THREAD

**Issue by Mabus13** [CobaltFusion/DebugViewPP#369]
Hello man! Very nice tool! Big thanks for your work. ^___^ (im from rus, sry 4 bad eng)
Can you add few new types of "filters": "start" and "end" highlitng/including/exluding. I try explain - after match filter that line and all next lines in one color highlighting, after "end" match highlighting clear. And same for including, exluding... 
WBR from Russia with love =3

**Comment by janwilmans** [comment]
Thank you for the compliments! I love to see when my work is appreciated.
The feature you are requesting would require a fundamental redesign, because the filters now operate line-by-line, but this kind of filter would be one where any previous line can change the appearance of later lines.

**Comment by Mabus13** [comment]
So no any hope for that feature?

**Comment by Mabus13** [comment]
Maybe for without "fundamental redesign" just use flag? Only few global flags for that features? Flag on - use color/show/hide... Flag off do nothing. =)))

**Comment by janwilmans** [comment]
That would work only if you 'reprocess' all lines every time from the beginning to end. This doesn't scale will, debugview can now quickly jump from any point in the buffer to any other line in the buffer, but with such a feature that would cause long delays to reprocess all the lines in between, so I'm not sure how to implement this without quite a bit overhead, slowing down all other usecases, even when not using this.

**Comment by janwilmans** [comment]
wont fix
