### ISSUE TITLE
Support for Windows 10 on ARM64

### ISSUE THREAD

**Issue by frankh0** [CobaltFusion/DebugViewPP#376]
Please support and provide a version for Windows 10 on ARM64. I'm using s Samsung Galaxy Book Go with Qualcomm Snapdragon 7 processor running the latest Windows 10. It seems that the DebugView++ 32bit works in emulation mode, but it would be nice to have a native version. The 32bit version available of DebugView++ is also older than the 64bit version.
Compiling WTL based Apps for ARM64 is also no problem anymore. I've already compiled and tested a WTL base Application on ARM64.

**Comment by janwilmans** [comment]
I can't really do anything, because I have no way to test it.

**Comment by frankh0** [comment]
I was able to add a configuration for ARM64 to the project. The Project compiled but there is a Linker issue. The boost library 'libboost_date_time-vc141-mt-sgd-a64-1_69.lib' is not available. There are only libs for Intel x86 and x64 available.

**Comment by janwilmans** [comment]
Good work, boost needs to be compiled for the arm target, if its anything
like on the intel platform then its a fairly straightforward process.

Jan

**Comment by janwilmans** [comment]
now futher feedback received; I have no ARM target to develop on, if anyone wants this, please re-open the issue
