### ISSUE TITLE
Possible to auto align the text?

### ISSUE THREAD

**Issue by pepeu93** [CobaltFusion/DebugViewPP#377]
I mean, align the text printed to the output something like:
![image](https://user-images.githubusercontent.com/82878129/133006732-d4c4e66c-97d7-4ba8-a1e0-6f33349150b1.png)

**Comment by janwilmans** [comment]
It will do this if you send it that way... tabs mare supported as well.
Debugview can't know how/what to align so you have to that yourself.
Selecting a proportionally spaced font like Courier otherwise it won't look
right...
