### ISSUE TITLE
Can't see all Message Text (shows "...")

### ISSUE THREAD

**Issue by dbareis** [CobaltFusion/DebugViewPP#380]
In Windows 11 the columns can't be resized and very long lines show "..." at the end.

Making the window wider to show all and then thinner again works to remove the "..." and show the rest of the line.  The last line should be as long as it need be and show a horizonal slider as most would expect it to.

**Comment by janwilmans** [comment]
I use windows 11 myself, and I don't see the problem that columns cannot be resized? Do you mean, the right-most 'message' column you cannot make bigger then the window?

Can I ask you to create a animated gif (like the one below) to show me the problem? (its very easy to create with this free software https://github.com/NickeManarin/ScreenToGif)


![debugview_column_resize](https://user-images.githubusercontent.com/5933444/176633226-d61ce6d3-7972-43cc-823a-4dce9b3f2e09.gif)

**Comment by janwilmans** [comment]
no feedback for 6 months, closing.
