### ISSUE TITLE
The log output is incorrect

### ISSUE THREAD

**Issue by ZRR666** [CobaltFusion/DebugViewPP#382]
DebugViewPP does not support Korean language

Is it printed??

**Comment by ZRR666** [comment]
![image](https://user-images.githubusercontent.com/41984214/178096169-0ff67c16-7052-4fce-ba60-2296c5f18173.png)
L"abccccc 게임 시작"

**Comment by ZRR666** [comment]
![image](https://user-images.githubusercontent.com/41984214/178096241-ce80c4ec-9d42-43cf-a302-79d5802dec50.png)

**Comment by janwilmans** [comment]
OutputDebugStringW internally converts the strings and calls OutputDebugStringA, so there is nothing I can change to support WideStrings. However, if you can call OutputDebugStringA and give to UTF-8 input, that can work out of the box.

There are a couple of windows settings that need to be enabled for it to work:
![image](https://user-images.githubusercontent.com/5933444/178105868-385feb73-88e4-4605-b0fe-78ede7f346cf.png)

![image](https://user-images.githubusercontent.com/5933444/178105873-d9d58a47-6e47-4c83-b215-1f7b6682d71c.png)

I tested with Chinese, but it should work for Korean the same way.

**Comment by janwilmans** [comment]
no further feedback received, please reopen if needed
