### ISSUE TITLE
Cannot compile due to 1.8.103-x64 due to boost error

### ISSUE THREAD

**Issue by tephyrnex** [CobaltFusion/DebugViewPP#384]
I wouldn't submit the issue if I hadn't tried everything that I can think of to correct this.  

I consistently get the following error when trying to compile the solution in VS2019...either HEAD or TAG 1.8.103-x64.

DebugViewPP\packages\boost.1.69.0.0\lib\native\include\boost\signals2\detail\auto_buffer.hpp(145,37): error C2039: 'pointer': is not a member of 'std::allocator<T>'

I have tried reverting the boost library, VS2017, VS2019, VS2022.  I have tried pulling previous TAGs (usually get different errors).

I've tried numerous workarounds.  Any insight would be appreciated.

**Comment by WebDancer69** [comment]
Upgrading to a conformant boost worked for me, i.e. boost v1.79 v142.

All packages,config: replace "1.69.0.0" with "1.79.0.0", replace "-vc141" with "-vc142"
All *.vcxproj: replace "1.69.0.0" with "1.79.0", replace "-vc141" with "-vc142"

Note the dropped ".0" in the paths (vcxproj).

**Comment by tephyrnex** [comment]
Thanks, @WebDancer69!  That did the trick.  Do you know if there is an outstanding pull request fro this?

**Comment by WebDancer69** [comment]
Sorry @tephyrnex, I don't know of any such PR. It seems the build is a bit of a mess, with several unused (?) solution build configs, and 32-bit and 64-bit builds does not target the same VS version.

**Comment by tephyrnex** [comment]
Agreed...the build is a bit of a mess right now; however, your suggestion got me going...so Cheers!

**Comment by janwilmans** [comment]
The setup was made like this so it's still possible to compile with very old versions of visual studio, it might be time to move away from that and make the configuration cleaner

**Comment by janwilmans** [comment]
I've updated the project to use cmake and a new boost version 1.80, please give it a try.
