### ISSUE TITLE
Unable to build the DebugViewConsole project out of the box

### ISSUE THREAD

**Issue by MadangLightHouse** [CobaltFusion/DebugViewPP#390]
I am unable to build the DebugViewConsole project out of the box. The issue is a missing file - 'docopt.h'.

See attached image.

![image](https://github.com/CobaltFusion/DebugViewPP/assets/14177916/ffe4aa82-e446-489d-905e-be149a5128c1)

I've searched the downloaded source base, but the file was not included in the ZIP.

I am building using Visual Studio 2022 (v143) & ISO C++17 Standard (/std:c++17).

Love your work.

Cheers

**Comment by janwilmans** [comment]
how are you building?
that file is here: https://github.com/CobaltFusion/DebugViewPP/blob/develop/application/Libraries/docopt.cpp/docopt.h

**Comment by janwilmans** [comment]
closed due to positive re-test and no further reaction
