### ISSUE TITLE
VirusTotal detects trojan in 1.9.0.24 via Google and 5 other vendors

### ISSUE THREAD

**Issue by roman-orekhov** [CobaltFusion/DebugViewPP#394]
This is probably a false positive due to UPX compression, but here is the [report](https://www.virustotal.com/gui/file/29868dfa051000848e4c409707e373997c649009d3f677dafa2236f9fb89759f). Eyebrow raises on flagging by Google.
Previous release had only [one detection](https://www.virustotal.com/gui/file/35fe7bf1713e5ffc0d89fb00e58deae414165fe4e8e0326a09a63cb040818c7e).

Is it possible to make no-UPX releases?

**Comment by janwilmans** [comment]
sure, I'll make a second no-upx release, no problem

**Comment by janwilmans** [comment]
It still detects one thing: 

[debugviewpp-1.9.0.24-win64-upx.zip](https://github.com/CobaltFusion/DebugViewPP/releases/download/v1.9.0.24/debugviewpp-1.9.0.24-win64-upx.zip)
631 KB

[debugviewpp-1.9.0.24-win64.zip](https://github.com/CobaltFusion/DebugViewPP/releases/download/v1.9.0.24/debugviewpp-1.9.0.24-win64.zip)

![image](https://github.com/CobaltFusion/DebugViewPP/assets/5933444/77cc98f5-33d2-4092-abab-2cac75babed5)

https://www.virustotal.com/gui/file/2a14df7fa530ef2de3ee0834e574a86b2797b0c1319f484fdd63e30b272450b8?nocache=1

![image](https://github.com/CobaltFusion/DebugViewPP/assets/5933444/e0d5c26e-6ada-480a-9004-4369122c4f75)

https://www.virustotal.com/gui/file/29868dfa051000848e4c409707e373997c649009d3f677dafa2236f9fb89759f

**Comment by janwilmans** [comment]
I find it interesting that this detection:
![image](https://github.com/CobaltFusion/DebugViewPP/assets/5933444/c2a202fb-4c16-49c1-8a39-f63008cd1b65)

Is not found on the UPX version:
![image](https://github.com/CobaltFusion/DebugViewPP/assets/5933444/9512042e-292c-4938-a844-2711ac41062e)
